spring:
  application:
    name:
      BookShop-API
  datasource:
    url: jdbc:mysql://localhost:3306/bookshop_api?createDatabaseIfNotExist=true&autoReconnect=true&userSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: a123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update



jwt:
  secret: minhnn_jwt