spring:
  application:
    name:
      BookShop-API
  datasource:
    url: jdbc:mysql://localhost:3306/bookshop_api?createDatabaseIfNotExist=true&autoReconnect=true&userSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: a123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  #config mail
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: bookshops.app@gmail.com
    password: yhzh wuhn xxlh lmhe
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true
  #set-max-file-size
  servlet:
    multipart:
      max-request: 6MB
      max-file-size: 3MB

jwt:
  secret: minhnn_jwt